import json

import pytest
import yaml

from aos import kiroflow
from aos.board import Board
from aos.errors import AosError


@pytest.fixture
def board(data):
    b = Board(data)
    b.create_feature("checkout", "Checkout v2")
    a = b.add_task("checkout", "api", "Orders endpoint")
    b.add_task("checkout", "web", "Checkout UI", depends_on=[a])
    return b


def nodes(recipe):
    """Every node in the tree, depth first."""
    out = []

    def walk(n):
        out.append(n)
        for child in n.get("steps", []) + n.get("branches", []):
            walk(child)

    for n in recipe["steps"]:
        walk(n)
    return out


def test_recipe_shape(board):
    r = kiroflow.build_recipe(board, "checkout", aos_bin="/x/bin/aos", poll=30)
    assert r["name"] == "aos-checkout" and "Checkout v2" in r["description"]
    top = r["steps"]
    assert [n["id"] for n in top] == ["start", "tasks", "summary"]
    assert "board_start" in top[0]["prompt"] and '"checkout"' in top[0]["prompt"]
    par = top[1]
    assert par["type"] == "parallel" and par["joinPolicy"] == "allSettled"
    loops = par["branches"]
    assert [l["id"] for l in loops] == ["task-1", "task-2"]
    for l, tid in zip(loops, (1, 2)):
        assert l["type"] == "repeat" and l["stopWhen"] == f"watch-t{tid}.terminal"
        assert l["maxIterations"] == 20 and l["onMaxIterations"] == "pause"
        watch, handle = l["steps"]
        assert watch == {"type": "watch", "id": f"watch-t{tid}", "handler": "command",
                         "config": {"command": f"/x/bin/aos board watch --task {tid}",
                                    "pollIntervalSec": 30, "commandTimeoutSec": 20}}
        assert handle["id"] == f"handle-t{tid}" and f"{{{{watch-t{tid}.output}}}}" in handle["prompt"]
        for tool in ("task_unblock", "proposal_decide", "task_retry", "board_start"):
            assert tool in handle["prompt"]
    assert "board_status" in top[2]["prompt"]


def test_only_bundled_agents_and_never_implement(board):
    r = kiroflow.build_recipe(board, "checkout", aos_bin="aos")
    agents = {n["agent"] for n in nodes(r) if n["type"] == "step"}
    assert agents == {"wf-planner"}
    for n in nodes(r):
        if n["type"] == "step":
            assert "Do not edit files" in n["prompt"]


def test_limits(board, data):
    with pytest.raises(AosError, match="10"):
        kiroflow.build_recipe(board, "checkout", aos_bin="aos", poll=5)
    big = Board(data, max_tasks_per_feature=100)
    big.create_feature("huge", "Huge")
    for i in range(17):
        big.add_task("huge", "api", f"t{i}")
    with pytest.raises(AosError, match="aos board run"):
        kiroflow.build_recipe(big, "huge", aos_bin="aos")
    empty = Board(data)
    empty.create_feature("empty", "Empty")
    with pytest.raises(AosError, match="no tasks"):
        kiroflow.build_recipe(empty, "empty", aos_bin="aos")


def test_write_recipe(board, tmp_path):
    path = kiroflow.write_recipe(board, "checkout", tmp_path / "proj", aos_bin="aos")
    assert path == tmp_path / "proj/.kiro/workflows/aos-checkout.workflow.yaml"
    assert yaml.safe_load(path.read_text())["name"] == "aos-checkout"
    assert path.read_text().startswith("# Generated by agenticOS")
