"""Generate a Kiro workflow recipe that fronts the aos board for one feature.

The aos board still executes (dispatcher, worktrees, Claude/Kiro workers); the
recipe gives Kiro users a Workflows-panel view with one zero-token watch loop per
task, and asks them inside Kiro when a task is blocked, failed, or proposes a
contract change. Constraints come from spikes/kiro-workflows/FINDINGS.md:
bundled step agents only, `*.workflow.yaml`, pollIntervalSec >= 10, <= 50 nodes,
and a watch node completes on its first `new-activity`.
"""

from __future__ import annotations

from pathlib import Path

import yaml

from .board import Board
from .errors import AosError
from .store import write_atomic

STEP_AGENT = "wf-planner"
MAX_NODES = 50
MIN_POLL = 10
NO_EDITS = "Do not edit files and do not implement any task yourself; the aos board workers do the work."


def _step(node_id: str, prompt: str) -> dict:
    return {"type": "step", "id": node_id, "agent": STEP_AGENT, "prompt": prompt.strip() + "\n"}


def _handle_prompt(slug: str, t: dict) -> str:
    n = t["id"]
    return f"""
Task #{n} ({t['project']}): {t['title']}. Feature "{slug}".
The board watch reported (JSON): {{{{watch-t{n}.output}}}}

{NO_EDITS} Do not edit files.
Read the report and call the aos tool board_status("{slug}") if you need more detail. Then:
- status "blocked": send_message with severity warning, quoting the blocker and asking the user how to proceed.
  When the user answers, call task_unblock({n}, note=<their answer>) and then board_start("{slug}").
- "proposals" present: show each change and reason with send_message severity warning and ask approve or reject.
  Call proposal_decide(<id>, approve=<true|false>, reason=<their words>) for each, then board_start("{slug}").
- status "failed": send_message severity warning with last_error, asking retry or cancel.
  Retry: task_retry({n}, note=<their guidance>) then board_start("{slug}"). Cancel: task_cancel({n}).
- status "done": report its result in one or two sentences.
Finish with send_message severity success summarising what you did.
"""


def build_recipe(board: Board, slug: str, aos_bin: str, poll: int = 30) -> dict:
    feature = board.feature(slug)
    tasks = board.tasks(feature=slug)
    if not tasks:
        raise AosError(f"feature {slug!r} has no tasks", "create tasks first (aos task add / task_create)")
    if int(poll) < MIN_POLL:
        raise AosError(f"poll interval must be at least {MIN_POLL} seconds (Kiro's minimum)")
    node_count = 3 + 3 * len(tasks)  # start, parallel, summary + (repeat, watch, step) per task
    if node_count > MAX_NODES:
        raise AosError(f"{len(tasks)} tasks need {node_count} workflow nodes but Kiro allows {MAX_NODES}: "
                       "split the feature, or drive it with `aos board run` instead")
    loops = []
    for t in tasks:
        n = t["id"]
        loops.append({
            "type": "repeat",
            "id": f"task-{n}",
            "maxIterations": 20,
            "onMaxIterations": "pause",
            "stopWhen": f"watch-t{n}.terminal",
            "steps": [
                {"type": "watch", "id": f"watch-t{n}", "handler": "command",
                 "config": {"command": f"{aos_bin} board watch --task {n}",
                            "pollIntervalSec": int(poll), "commandTimeoutSec": 20}},
                _step(f"handle-t{n}", _handle_prompt(slug, t)),
            ],
        })
    return {
        "name": f"aos-{slug}",
        "description": f"agenticOS feature {slug}: {feature['title']} "
                       f"({len(tasks)} tasks; generated by `aos feature workflow {slug}`)",
        "steps": [
            _step("start", f"""
Call the aos MCP tool board_start("{slug}") and report what it returned in one sentence.
{NO_EDITS} Do not edit files.
Finish with send_message severity success."""),
            {"type": "parallel", "id": "tasks", "joinPolicy": "allSettled", "branches": loops},
            _step("summary", f"""
Call the aos MCP tool board_status("{slug}") and write a short final report: each task with its
status and the first line of its result, anything still blocked or pending, and where the work is:
~/.agenticos/worktrees/{slug}/<project> on branch feature/{slug} (never pushed; the user reviews and merges).
{NO_EDITS} Do not edit files.
Finish with send_message severity success containing the report."""),
        ],
    }


def write_recipe(board: Board, slug: str, workspace: str | Path, aos_bin: str, poll: int = 30) -> Path:
    recipe = build_recipe(board, slug, aos_bin, poll)
    path = Path(workspace) / ".kiro" / "workflows" / f"aos-{slug}.workflow.yaml"
    header = (f"# Generated by agenticOS from board feature {slug!r}. Re-generate with:\n"
              f"#   aos feature workflow {slug}\n# Run it from Kiro's Workflows panel. Local to this machine.\n")
    write_atomic(path, header + yaml.safe_dump(recipe, sort_keys=False, allow_unicode=True, width=100))
    return path
